### ISSUE TITLE
sensitivity randomly spikes

### ISSUE THREAD

**Issue by jackal329** [W11cE/XIM-Link#19]
playing MW3 on Xbox 360.

at random times my mouse sensitivity spikes. i'll usually notice when I jump throw a c4, my aim goes straight up to the sky. I press alt to throw the c4, space to jump and then move my mouse upwards. Sometimes it's fine but other times sensitivity goes wonky!

This happens when I'm doing drop shots too but instead my mouse goes left and right too fast. Even if I gently move my mouse it'll jump all over on the ingame screen. 

I didn't mess with any ballistic curve settings or anything like that. Just set my sensitivity and that's it. I used the Xim 4 / sandhawc without issue and have been having troubles ever since switching to xim apex / link.

xim link 1.2
[DxDiag.txt](https://github.com/W11cE/XIM-Link/files/2364017/DxDiag.txt)

**Comment by jackal329** [comment]
mouse accel is off. enhanced pointer precision is off in windows control panel. acceleration unchecked in logitech control panel as well.

**Comment by Huffy16** [comment]
Do you have anything with ADS set to toggle? I noticed when I I had space (or the A button) had a deactivation set for toggle my sens went crazy .. changed the deactivation key and it fixed the issue .. hoped it helps

**Comment by jackal329** [comment]
No, I don't. I found the issue and posted about it here: https://community.xim.tech/index.php?topic=69799.0
